---
image: registry.gitlab.inria.fr/vtaverni/libshadertoy/build-stretch:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  stage: deploy
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make shadertoy_doc
    - mv html ../public
  artifacts:
    paths:
      - public
  only:
    - master

# vim: set et:ts=2:sw=2:
