---
variables:
  STRETCH_AMD64_TEST_IMAGE: registry.gitlab.inria.fr/vtaverni/libshadertoy/amd64/build-stretch:$CI_COMMIT_REF_SLUG
  STRETCH_AMD64_RELEASE_IMAGE: registry.gitlab.inria.fr/vtaverni/libshadertoy/amd64/build-stretch:latest
  STRETCH_I386_TEST_IMAGE: registry.gitlab.inria.fr/vtaverni/libshadertoy/i386/build-stretch:$CI_COMMIT_REF_SLUG
  STRETCH_I386_RELEASE_IMAGE: registry.gitlab.inria.fr/vtaverni/libshadertoy/i386/build-stretch:latest
  BUSTER_AMD64_TEST_IMAGE: registry.gitlab.inria.fr/vtaverni/libshadertoy/amd64/build-buster:$CI_COMMIT_REF_SLUG
  BUSTER_AMD64_RELEASE_IMAGE: registry.gitlab.inria.fr/vtaverni/libshadertoy/amd64/build-buster:latest
  BUSTER_I386_TEST_IMAGE: registry.gitlab.inria.fr/vtaverni/libshadertoy/i386/build-buster:$CI_COMMIT_REF_SLUG
  BUSTER_I386_RELEASE_IMAGE: registry.gitlab.inria.fr/vtaverni/libshadertoy/i386/build-buster:latest
  BIONIC_AMD64_TEST_IMAGE: registry.gitlab.inria.fr/vtaverni/libshadertoy/amd64/build-bionic:$CI_COMMIT_REF_SLUG
  BIONIC_AMD64_RELEASE_IMAGE: registry.gitlab.inria.fr/vtaverni/libshadertoy/amd64/build-bionic:latest
  BIONIC_I386_TEST_IMAGE: registry.gitlab.inria.fr/vtaverni/libshadertoy/i386/build-bionic:$CI_COMMIT_REF_SLUG
  BIONIC_I386_RELEASE_IMAGE: registry.gitlab.inria.fr/vtaverni/libshadertoy/i386/build-bionic:latest


stages:
  - build_images
  - build
  - deploy
  - release

.fetch_submodules: &fetch_submodules
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

.docker_op: &docker_op
  image: docker:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.inria.fr
  tags:
    - linux

.build_image: &build_image
  <<: *docker_op
  stage: build_images

.build_pkg: &build_pkg
  <<: *fetch_submodules
  stage: build
  script:
    - make gl
  tags:
    - linux

.release_img: &release_img
  <<: *docker_op
  stage: release

bionic_amd64_image:
  <<: *build_image
  script:
    - docker pull $BIONIC_AMD64_TEST_IMAGE || true
    - docker build --pull -t $BIONIC_AMD64_TEST_IMAGE --cache-from $BIONIC_AMD64_TEST_IMAGE -f docker/Dockerfile.bionic-amd64 docker
    - docker push $BIONIC_AMD64_TEST_IMAGE

bionic_i386_image:
  <<: *build_image
  script:
    - docker pull $BIONIC_I386_TEST_IMAGE || true
    - docker build --pull -t $BIONIC_I386_TEST_IMAGE --cache-from $BIONIC_I386_TEST_IMAGE -f docker/Dockerfile.bionic-i386 docker
    - docker push $BIONIC_I386_TEST_IMAGE

bionic_amd64_pkg:
  <<: *build_pkg
  image: $BIONIC_AMD64_TEST_IMAGE
  artifacts:
    name: 'libshadertoy-bionic-amd64-$CI_COMMIT_REF_SLUG'
    paths:
      - '*.deb'

bionic_i386_pkg:
  <<: *build_pkg
  image: $BIONIC_I386_TEST_IMAGE
  artifacts:
    name: 'libshadertoy-bionic-i386-$CI_COMMIT_REF_SLUG'
    paths:
      - '*.deb'

release_bionic_amd64_image:
  <<: *release_img
  script:
    - docker pull $BIONIC_AMD64_TEST_IMAGE || true
    - docker tag $BIONIC_AMD64_TEST_IMAGE $BIONIC_AMD64_RELEASE_IMAGE
    - docker push $BIONIC_AMD64_RELEASE_IMAGE
  only:
    - master

release_bionic_i386_image:
  <<: *release_img
  script:
    - docker pull $BIONIC_I386_TEST_IMAGE || true
    - docker tag $BIONIC_I386_TEST_IMAGE $BIONIC_I386_RELEASE_IMAGE
    - docker push $BIONIC_I386_RELEASE_IMAGE
  only:
    - master

stretch_amd64_image:
  <<: *build_image
  script:
    - docker pull $STRETCH_AMD64_TEST_IMAGE || true
    - docker build --pull -t $STRETCH_AMD64_TEST_IMAGE --cache-from $STRETCH_AMD64_TEST_IMAGE -f docker/Dockerfile.stretch-amd64 docker
    - docker push $STRETCH_AMD64_TEST_IMAGE

stretch_i386_image:
  <<: *build_image
  script:
    - docker pull $STRETCH_I386_TEST_IMAGE || true
    - docker build --pull -t $STRETCH_I386_TEST_IMAGE --cache-from $STRETCH_I386_TEST_IMAGE -f docker/Dockerfile.stretch-i386 docker
    - docker push $STRETCH_I386_TEST_IMAGE

stretch_amd64_pkg:
  <<: *build_pkg
  image: $STRETCH_AMD64_TEST_IMAGE
  artifacts:
    name: 'libshadertoy-stretch-amd64-$CI_COMMIT_REF_SLUG'
    paths:
      - '*.deb'

stretch_i386_pkg:
  <<: *build_pkg
  image: $STRETCH_I386_TEST_IMAGE
  artifacts:
    name: 'libshadertoy-stretch-i386-$CI_COMMIT_REF_SLUG'
    paths:
      - '*.deb'

win10_amd64_pkg:
  <<: *fetch_submodules
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=E:\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 15 2017 Win64" ..
    - cmake --build . --config Release -- /m
    - cmake --build . --config Release --target PACKAGE -- /m
    - move libshadertoy-*.7z ..
  artifacts:
    name: 'libshadertoy-win10-amd64-%CI_COMMIT_REF_SLUG%'
    paths:
      - '*.7z'
  tags:
    - windows

release_stretch_amd64_image:
  <<: *release_img
  script:
    - docker pull $STRETCH_AMD64_TEST_IMAGE
    - docker tag $STRETCH_AMD64_TEST_IMAGE $STRETCH_AMD64_RELEASE_IMAGE
    - docker push $STRETCH_AMD64_RELEASE_IMAGE
  only:
    - master

release_stretch_i386_image:
  <<: *release_img
  script:
    - docker pull $STRETCH_I386_TEST_IMAGE
    - docker tag $STRETCH_I386_TEST_IMAGE $STRETCH_I386_RELEASE_IMAGE
    - docker push $STRETCH_I386_RELEASE_IMAGE
  only:
    - master

buster_amd64_image:
  <<: *build_image
  script:
    - docker pull $BUSTER_AMD64_TEST_IMAGE || true
    - docker build --pull -t $BUSTER_AMD64_TEST_IMAGE --cache-from $BUSTER_AMD64_TEST_IMAGE -f docker/Dockerfile.buster-amd64 docker
    - docker push $BUSTER_AMD64_TEST_IMAGE

buster_i386_image:
  <<: *build_image
  script:
    - docker pull $BUSTER_I386_TEST_IMAGE || true
    - docker build --pull -t $BUSTER_I386_TEST_IMAGE --cache-from $BUSTER_I386_TEST_IMAGE -f docker/Dockerfile.buster-i386 docker
    - docker push $BUSTER_I386_TEST_IMAGE

buster_amd64_pkg:
  <<: *build_pkg
  image: $BUSTER_AMD64_TEST_IMAGE
  artifacts:
    name: 'libshadertoy-buster-amd64-$CI_COMMIT_REF_SLUG'
    paths:
      - '*.deb'

buster_i386_pkg:
  <<: *build_pkg
  image: $BUSTER_I386_TEST_IMAGE
  artifacts:
    name: 'libshadertoy-buster-i386-$CI_COMMIT_REF_SLUG'
    paths:
      - '*.deb'

release_buster_amd64_image:
  <<: *release_img
  script:
    - docker pull $BUSTER_AMD64_TEST_IMAGE || true
    - docker tag $BUSTER_AMD64_TEST_IMAGE $BUSTER_AMD64_RELEASE_IMAGE
    - docker push $BUSTER_AMD64_RELEASE_IMAGE
  only:
    - master

release_buster_i386_image:
  <<: *release_img
  script:
    - docker pull $BUSTER_I386_TEST_IMAGE || true
    - docker tag $BUSTER_I386_TEST_IMAGE $BUSTER_I386_RELEASE_IMAGE
    - docker push $BUSTER_I386_RELEASE_IMAGE
  only:
    - master

pages:
  <<: *fetch_submodules
  stage: deploy
  image: $STRETCH_AMD64_TEST_IMAGE
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make shadertoy_doc
    - mv html ../public
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - linux

# vim: set et:ts=2:sw=2:
